# .streamlit/secrets.toml
SUPABASE_URL = "https://gbfdgtvvegyefhlztodw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiZmRndHZ2ZWd5ZWZobHp0b2R3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MDQxODU3NCwiZXhwIjoyMDk1OTk0NTc0fQ.bel_ewlfBOMbbutvrWjADEUTAXFgWKFi839h5LDhi30"